### ISSUE TITLE
Consider using `command` instead of `shell` when `bash` specific commands aren't required

### ISSUE THREAD

**Issue by elfiesmelfie** [infrawatch/functional-tests#6]
Just FYI you might want to suggest using `command` instead of `shell` when `bash` specific commands aren't required as that's the preferred (safer) way to execute things. I wouldn't hold this up though since the risk is pretty low I think.

_Originally posted by @leifmadsen in https://github.com/infrawatch/functional-tests/pull/5#r475599489_

**Comment by elfiesmelfie** [comment]
command case easily be inserted where there aren't any shell vars, or console redirection (<, >, |) used, but we are using a lot of those.
There might be a few place where the shell can be replaces with something else, but it is low risk, except maybe when someone passes an arbitrary value to container_bin, collectd_container_name or qdr_container_name

**Comment by leifmadsen** [comment]
If there isn't a large number of s/shell/command/ then you can drop this issue as "not an issue" :)

**Comment by elfiesmelfie** [comment]
There's one instance, but I did need to check when was appropriate to use command instead of shell. At the very least, I'll be aware of the when updating the tests.
